import type {
  ConversationItem,
  IcemanConfig,
  MessageItem,
  PotentialConnection,
  PersonaTemplate,
  SummaryCard,
  UserProfile,
} from '../types/models';

const now = 1_775_382_000;

export const OWNER_IM_SESSION_ID = 'owner-im';
export const PRIMARY_VISITOR_SESSION_ID = 'sess_visitor456_20260405';

export const ownerProfile: UserProfile = {
  open_id: 'owner_user_123',
  nickName: '冬日暖阳',
  avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=owner',
  gender: 1,
  city: '北京',
  province: '北京',
  country: '中国',
  role: 'host',
  interests: ['滑雪', '摄影', '咖啡'],
  bio: '喜欢在雪山和街头捕捉光，也喜欢和真诚的人慢慢聊天。',
  iceman_nickname: '小暖',
};

export const visitorProfile: UserProfile = {
  open_id: 'visitor_user_456',
  nickName: '阳光少年',
  avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=visitor-main',
  gender: 1,
  city: '乌鲁木齐',
  province: '新疆',
  country: '中国',
  role: 'visitor',
  interests: ['滑雪', '阿勒泰', '户外'],
  bio: '一到冬天就想往雪场跑。',
};

export const icemanProfile = {
  avatarUrl: 'https://api.dicebear.com/9.x/bottts/svg?seed=iceman-blue',
};

export const personaTemplates: PersonaTemplate[] = [
  {
    template_id: 'persona_001',
    name: '活泼可爱型',
    description: '性格开朗，语气轻快，适合轻松破冰和兴趣延展。',
    example_dialogue: '嗨～今天也有认真帮你和新朋友聊天，我先替你暖个场呀。',
  },
  {
    template_id: 'persona_002',
    name: '知性温柔型',
    description: '语气沉稳温柔，适合深度聊天和建立安全感。',
    example_dialogue: '你好呀，我会尽量把聊天节奏放舒服一点，也会替你守住边界。',
  },
  {
    template_id: 'persona_003',
    name: '克制清爽型',
    description: '表达简洁，低打扰，适合想提高筛选效率的场景。',
    example_dialogue: '收到，我会更简洁地接话，把重点留给真正值得聊的人。',
  },
];

export const configState: IcemanConfig = {
  iceman_id: 'iceman_owner123',
  owner_user_id: ownerProfile.open_id,
  nickname: 'yolo的小冰人',
  status: 'enabled',
  persona_template_id: personaTemplates[0].template_id,
  persona_name: personaTemplates[0].name,
};

export const conversations: ConversationItem[] = [
  {
    session_id: OWNER_IM_SESSION_ID,
    conversation_type: 'owner_im',
    peer_user: ownerProfile,
    owner_id: ownerProfile.open_id,
    iceman_id: configState.iceman_id,
    status: 'ai_chatting',
    is_folded: false,
    unread_count: 2,
    last_message: {
      content_brief: '今天共有 3 位访客聊得很顺，我把总结卡片整理好了。',
      timestamp: now - 60,
    },
    visitor_interest_tags: [],
    filter_reason: '',
    created_at: now - 7200,
    last_message_at: now - 60,
    takeover_at: null,
    is_owner_session: true,
  },
  {
    session_id: PRIMARY_VISITOR_SESSION_ID,
    conversation_type: 'host_visitor',
    peer_user: visitorProfile,
    owner_id: ownerProfile.open_id,
    iceman_id: configState.iceman_id,
    status: 'ai_chatting',
    is_folded: false,
    unread_count: 2,
    last_message: {
      content_brief: '我下个月想去阿勒泰，你主人会推荐路线吗？',
      timestamp: now - 320,
    },
    visitor_interest_tags: ['滑雪', '阿勒泰', '路线攻略'],
    filter_reason: '',
    created_at: now - 3200,
    last_message_at: now - 320,
    takeover_at: null,
  },
  {
    session_id: 'sess_visitor202_20260405',
    conversation_type: 'host_visitor',
    peer_user: {
      open_id: 'visitor_user_202',
      nickName: '晨光咖啡',
      avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=visitor-takeover',
      gender: 2,
      city: '杭州',
      province: '浙江',
      country: '中国',
      role: 'visitor',
      interests: ['咖啡', '摄影', '展览'],
      bio: '喜欢去陌生城市看展，再找一家好喝的咖啡店。',
    },
    owner_id: ownerProfile.open_id,
    iceman_id: configState.iceman_id,
    status: 'host_takeover',
    is_folded: false,
    unread_count: 1,
    last_message: {
      content_brief: '如果你下次去杭州看展，我可以给你做一份咖啡地图。',
      timestamp: now - 80,
    },
    visitor_interest_tags: ['咖啡', '摄影', '杭州'],
    filter_reason: '',
    created_at: now - 2800,
    last_message_at: now - 80,
    takeover_at: now - 240,
  },
  {
    session_id: 'sess_visitor001_20260405',
    conversation_type: 'host_visitor',
    peer_user: {
      open_id: 'visitor_user_001',
      nickName: '老派搭讪王',
      avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=visitor-folded',
      gender: 1,
      city: '上海',
      province: '上海',
      country: '中国',
      role: 'visitor',
      interests: ['低质搭讪'],
      bio: '热衷于复制粘贴式开场白。',
    },
    owner_id: ownerProfile.open_id,
    iceman_id: configState.iceman_id,
    status: 'filtered_folded',
    is_folded: true,
    unread_count: 0,
    last_message: {
      content_brief: '这个方向先不展开啦，我们还是聊视频和兴趣吧。',
      timestamp: now - 150,
    },
    visitor_interest_tags: ['低质搭讪'],
    filter_reason: '在线意图分类识别为不当请求，已折叠展示。',
    created_at: now - 1200,
    last_message_at: now - 150,
    takeover_at: null,
  },
  {
    session_id: 'sess_visitor999_20260405',
    conversation_type: 'host_visitor',
    peer_user: {
      open_id: 'visitor_user_999',
      nickName: '流量增长助手',
      avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=visitor-blocked',
      gender: 0,
      city: '深圳',
      province: '广东',
      country: '中国',
      role: 'visitor',
      interests: ['导流', '推广'],
      bio: '高频发送推广导流消息。',
    },
    owner_id: ownerProfile.open_id,
    iceman_id: configState.iceman_id,
    status: 'filtered_blocked',
    is_folded: true,
    unread_count: 0,
    last_message: {
      content_brief: '兼职拉新福利群，要不要进一下？',
      timestamp: now - 500,
    },
    visitor_interest_tags: ['推广', '导流'],
    filter_reason: '离线过滤判定为广告导流，已升级为 blocked。',
    created_at: now - 1800,
    last_message_at: now - 500,
    takeover_at: null,
  },
];

export const messages: Record<string, MessageItem[]> = {
  [OWNER_IM_SESSION_ID]: [
    {
      message_id: 'owner-msg-1',
      sender_type: 'IceMan',
      sender_id: configState.iceman_id,
      sender_name: configState.nickname,
      content: '主人，今天我会参考你和我最近 6 条 IM 对话来决定回复语气，也会继续守住隐私边界。',
      content_type: 'text',
      timestamp: now - 7200,
    },
    {
      message_id: 'owner-msg-2',
      sender_type: 'Host',
      sender_id: ownerProfile.open_id,
      sender_name: ownerProfile.nickName,
      content: '好，最近如果有人聊滑雪和阿勒泰可以多接一点，但不要说我具体什么时候出发。',
      content_type: 'text',
      timestamp: now - 2600,
    },
    {
      message_id: 'owner-msg-3',
      sender_type: 'IceMan',
      sender_id: configState.iceman_id,
      sender_name: configState.nickname,
      content: '记住啦。我会优先围绕你最近的视频、阿勒泰粉雪和摄影爱好来破冰，不会暴露行程和联系方式。',
      content_type: 'text',
      timestamp: now - 2200,
    },
    {
      message_id: 'owner-msg-4',
      sender_type: 'IceMan',
      sender_id: configState.iceman_id,
      sender_name: configState.nickname,
      content: '今天共有 3 位访客聊得比较顺，我已经整理了一张总结卡片给你。',
      content_type: 'text',
      timestamp: now - 60,
    },
  ],
  [PRIMARY_VISITOR_SESSION_ID]: [
    {
      message_id: 'va-1',
      sender_type: 'Visitor',
      sender_id: visitorProfile.open_id,
      sender_name: visitorProfile.nickName,
      content: '你好呀，听说你主人最近在准备阿勒泰的雪季？',
      content_type: 'text',
      timestamp: now - 1800,
    },
    {
      message_id: 'va-2',
      sender_type: 'IceMan',
      sender_id: configState.iceman_id,
      sender_name: configState.nickname,
      content: '对呀，她最近一直在看阿勒泰和可可托海的路线，还在纠结到底先冲粉雪还是先拍日出。你也喜欢滑雪吗？',
      content_type: 'text',
      timestamp: now - 1760,
    },
    {
      message_id: 'va-3',
      sender_type: 'Visitor',
      sender_id: visitorProfile.open_id,
      sender_name: visitorProfile.nickName,
      content: '我每年都去阿勒泰，最喜欢将军山那种又松又软的雪感。你主人如果第一次去，我可以给她避坑路线。',
      content_type: 'text',
      timestamp: now - 1200,
    },
    {
      message_id: 'va-4',
      sender_type: 'IceMan',
      sender_id: configState.iceman_id,
      sender_name: configState.nickname,
      content: '哇，这个她一定会认真听！她最近就很想找真正懂阿勒泰的人聊路线，尤其在意拍照点和新手别踩雷的地方。',
      content_type: 'text',
      timestamp: now - 1160,
    },
    {
      message_id: 'va-5',
      sender_type: 'Visitor',
      sender_id: visitorProfile.open_id,
      sender_name: visitorProfile.nickName,
      content: '那太巧了，我下个月想再去一趟阿勒泰。你主人如果愿意，我可以先给她列个路线草稿。',
      content_type: 'text',
      timestamp: now - 320,
    },
  ],
  sess_visitor202_20260405: [
    {
      message_id: 'vb-1',
      sender_type: 'Visitor',
      sender_id: 'visitor_user_202',
      sender_name: '晨光咖啡',
      content: '刷到你主人的夜景视频了，构图很舒服，像是会认真看展的人。',
      content_type: 'text',
      timestamp: now - 900,
    },
    {
      message_id: 'vb-2',
      sender_type: 'IceMan',
      sender_id: configState.iceman_id,
      sender_name: configState.nickname,
      content: '她最近确实常去看展，也很爱用胶片感的方式拍城市。你平时也会边看展边找咖啡馆吗？',
      content_type: 'text',
      timestamp: now - 860,
    },
    {
      message_id: 'vb-3',
      sender_type: 'Visitor',
      sender_id: 'visitor_user_202',
      sender_name: '晨光咖啡',
      content: '会呀，我上周刚做了一张杭州摄影展和咖啡店地图，感觉你主人会喜欢这种路线。',
      content_type: 'text',
      timestamp: now - 620,
    },
    {
      message_id: 'vb-4',
      sender_type: 'System',
      sender_id: configState.iceman_id,
      sender_name: 'System',
      content: '主人觉得你很有趣，决定亲自和你聊聊～',
      content_type: 'text',
      timestamp: now - 260,
    },
    {
      message_id: 'vb-5',
      sender_type: 'Host',
      sender_id: ownerProfile.open_id,
      sender_name: ownerProfile.nickName,
      content: '这类路线我超吃，谢谢你！如果你方便的话，可以先把你最推荐的两个展和两家店告诉我。',
      content_type: 'text',
      timestamp: now - 80,
    },
  ],
  sess_visitor001_20260405: [
    {
      message_id: 'vc-1',
      sender_type: 'Visitor',
      sender_id: 'visitor_user_001',
      sender_name: '老派搭讪王',
      content: '美女，在吗？你长得像我下一个女朋友。',
      content_type: 'text',
      timestamp: now - 180,
    },
    {
      message_id: 'vc-2',
      sender_type: 'IceMan',
      sender_id: configState.iceman_id,
      sender_name: configState.nickname,
      content: '这个方向我先不接啦，我们还是聊聊主人的视频和兴趣吧。如果你也喜欢滑雪或摄影，我很愿意继续。',
      content_type: 'text',
      timestamp: now - 150,
    },
  ],
  sess_visitor999_20260405: [
    {
      message_id: 'vd-1',
      sender_type: 'Visitor',
      sender_id: 'visitor_user_999',
      sender_name: '流量增长助手',
      content: '兼职拉新福利群，要不要进一下？加微信我拉你。',
      content_type: 'text',
      timestamp: now - 540,
    },
  ],
};

export const blacklist: UserProfile[] = [
  {
    open_id: 'visitor_user_999',
    nickName: '流量增长助手',
    avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=blocked-a',
    gender: 0,
    city: '深圳',
  },
  {
    open_id: 'blocked_2',
    nickName: '夜聊机器人',
    avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=blocked-b',
    gender: 0,
    city: '未知',
  },
  {
    open_id: 'blocked_3',
    nickName: '广告投流助手',
    avatarUrl: 'https://api.dicebear.com/9.x/notionists/svg?seed=blocked-c',
    gender: 0,
    city: '未知',
  },
];

export const summaryCards: SummaryCard[] = [
  {
    summary_id: 'sum_20260405_owner123',
    owner_user_id: ownerProfile.open_id,
    date: '2026-04-05',
    visitor_count: 3,
    content:
      '今天共有 3 位访客与我对话。其中，阳光少年和你都喜欢滑雪，还主动提供了阿勒泰路线建议；晨光咖啡则和你一样偏爱摄影、展览与咖啡地图。',
    visitor_highlights: [
      {
        visitor_id: visitorProfile.open_id,
        nickName: visitorProfile.nickName,
        tags: ['滑雪', '阿勒泰', '路线攻略'],
        session_id: PRIMARY_VISITOR_SESSION_ID,
        status: 'ai_chatting',
      },
      {
        visitor_id: 'visitor_user_202',
        nickName: '晨光咖啡',
        tags: ['咖啡', '摄影', '杭州'],
        session_id: 'sess_visitor202_20260405',
        status: 'host_takeover',
      },
    ],
    deeplink: '/iceman/conversations?date=2026-04-05',
    generated_at: now - 40,
    pushed_at: now - 30,
  },
  {
    summary_id: 'sum_20260404_owner123',
    owner_user_id: ownerProfile.open_id,
    date: '2026-04-04',
    visitor_count: 2,
    content: '昨天有 2 位访客来聊天，一个对滑雪器材很懂，另一个聊了不少北京摄影展。',
    visitor_highlights: [
      {
        visitor_id: 'visitor_user_321',
        nickName: '雪场补给官',
        tags: ['装备', '滑雪'],
        session_id: 'sess_visitor321_20260404',
        status: 'ai_chatting',
      },
    ],
    deeplink: '/iceman/conversations?date=2026-04-04',
    generated_at: now - 86400,
  },
];

export const potentialConnections: Record<string, PotentialConnection> = {
  [PRIMARY_VISITOR_SESSION_ID]: {
    is_potential: true,
    reason: '访客不仅和主人有共同滑雪兴趣，还能提供阿勒泰一线经验，后续真实接聊价值高。',
  },
  sess_visitor202_20260405: {
    is_potential: true,
    reason: '访客在摄影、看展和咖啡地图上与主人有稳定交集，且表达具体、有延展空间。',
  },
  sess_visitor001_20260405: {
    is_potential: false,
    reason: '当前对话质量不足，不建议继续投入注意力。',
  },
};
